name: 中青分享

on:
  workflow_dispatch:
  schedule:
     - cron: '33 8,15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/guakeliao/garbageCollection.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【中青分享】'
        run: |  
          node Task/youthshare.js
